# Use an official Golang runtime as a parent image
FROM golang:latest

# Set the working directory to /app
RUN mkdir  /app

# Copy the current directory contents into the container at /app
COPY . /app

WORKDIR /app
# Build the Go app
RUN go build -o main .

CMD ["/app/main"]



